[config]
schemaVersion = "0.0.1"


[package]
namespace = "JarlUlsfark"
name = "Tools_of_the_Trade"
versionNumber = "1.0.4"
description = "A mod that adds 2 new Weapon Aspects: the Silver Spade (AKA NecroMel) and the Tablet of Peace (AKA KirbyMel)."
websiteUrl = "https://github.com/Tal-lev/Tools_of_the_Trade"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.70"
LuaENVY-ENVY = "1.2.0"
SGG_Modding-Chalk = "2.1.1"
SGG_Modding-ReLoad = "1.0.2"
SGG_Modding-SJSON = "1.0.0"
SGG_Modding-ModUtil = "4.0.1"
zerp-AspectExtender = "0.0.1"
NikkelM-Cosmetics_API = "1.1.4"

[package.rom_soft_deps]
# NikkelM-Zagreus_Journey = "1.2.0"
# ReadEmAndWeep-Flip_the_Arcana_Mod = "3.0.8"
# Wistiti-WrathOfOlympus = "2.3.1"
# Wistiti-HermesDuos = "1.0.1"
JarlUlsfark-UnderworldRites = "0.1.1"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"

[[build.copy]]
source = "./data"
target = "./plugins_data"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", ]
